apiVersion: v1
kind: Service
metadata:
  name: feastops-app-public
  namespace: feastops
  labels:
    app.kubernetes.io/name: feastops-app
    app.kubernetes.io/part-of: feastops
    app.kubernetes.io/exposure: public
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: feastops-app
  ports:
    - name: http
      port: 80
      targetPort: http
