apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - feastops-deployment.yaml
  - feastops-loadbalancer-service.yaml
  - feastops-pod-disruption-budget.yaml
  - feastops-hpa.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/environment: aws
