sonar.projectKey=feastops-food-delivery-api
sonar.projectName=FeastOps Food Delivery API
sonar.projectVersion=1.0.0
sonar.sources=src,public,Dockerfile
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/server.js
sonar.exclusions=coverage/**,node_modules/**,reports/**
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
